### ISSUE TITLE
Day: 22 July 2019

### ISSUE THREAD

**Issue by 2XL** [2XL/qianlispace.com#43]
**Motivation:**

Setup local dev environment

**Learning new tools:**
- docker 
- docker-compose

**Results for today**

- docker and docker-compose installed, hello world site composed with 4 services, image:version description 

 

1. -    - nginx:latest 
2. -    - mysql:latest 
3. -    - php:latest  site exposed through port 80
4. -    - php:latest site exposed through port 8080

hint: (this is not a valid manifest, may require small fixes)
```yaml

# docker-compose.yml
version
services
 nginx
  image: nginx
 backend:
  image: php
  port: 80
 frontend:
  image: php
  port: 8080
 database:
  image: mysql
  port: 3306


```
